name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Architecture
      run: echo "AMD_64"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libssl-dev libffi-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libucontext-dev
        pip3 install --user --upgrade buildozer cython virtualenv

    - name: Build with Buildozer
      run: |
        export PATH=$PATH:$HOME/.local/bin
        buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/*.apk
